### ISSUE TITLE
Failed to run on Anki 2.1.21

### ISSUE THREAD

**Issue by Junyu25** [CarryHJR/ContextHelper#1]
Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.21 (f1734a47) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-05-08 18:06:25

Caught exception:
```shell
Traceback (most recent call last):
  File "aqt\webview.py", line 30, in cmd
  File "aqt\webview.py", line 96, in _onCmd
  File "aqt\webview.py", line 422, in _onBridgeCmd
  File "<C:\Program Files\Anki\decorator.pyc:decorator-gen-64>", line 2, in onBridgeCmd
  File "lib\site-packages\anki\hooks.py", line 530, in decorator_wrapper
  File "lib\site-packages\anki\hooks.py", line 527, in repl
  File "C:\Users\***\AppData\Roaming\Anki2\addons21\516643804\main.py", line 135, in onBridge
    return _old(self, str)
  File "<C:\Program Files\Anki\decorator.pyc:decorator-gen-34>", line 2, in onBridgeCmd
  File "lib\site-packages\anki\hooks.py", line 530, in decorator_wrapper
  File "lib\site-packages\anki\hooks.py", line 527, in repl
  File "C:\Users\***\AppData\Roaming\Anki2\addons21\1463041493\main.py", line 341, in onBridgeCmd
    return _old(ed, cmd)
  File "aqt\editor.py", line 377, in onBridgeCmd
  File "C:\Users\***\AppData\Roaming\Anki2\addons21\823803971\getContext.py", line 154, in toggle_dict
    get_dict_html(editor, selection)
  File "C:\Users\***\AppData\Roaming\Anki2\addons21\823803971\getContext.py", line 145, in get_dict_html
    html_renren = get_renren(word)
  File "C:\Users\***\AppData\Roaming\Anki2\addons21\823803971\getContext.py", line 42, in get_renren
    tmp = soup.find_all(id="flexslider_2")[0].find_all("ul")[0].find_all("li")
IndexError: list index out of range
```

**Comment by CarryHJR** [comment]
你试一下先选中再点按钮，不行的话把你的选中的单词告诉我来测试

**Comment by Junyu25** [comment]
嗯嗯，可以了！
很棒的一款插件，
完全可以代替Word Query，
希望作者能够为它定制特定的卡片模板(PS: 将释义放到卡片的背面)
这样食用起来就完美了

**Comment by scq000** [comment]
好像卡死了 还能用吗？ 现在

**Comment by kkykkky** [comment]
请问大佬有时间能更新下插件吗，现在似乎不能用了
![image](https://user-images.githubusercontent.com/45260962/177194128-3add9356-f279-45db-b254-8660ae8f2bf0.png)

**Comment by CarryHJR** [comment]
真的有人还在继续用这个插件吗😭

**Comment by kkykkky** [comment]
> 真的有人还在继续用这个插件吗😭

是的，人人词典的资源真的很好，好不容易好不容易在anki插件库找到结果不能用。我重新装回2.1.15好像还是不行😭

**Comment by kkykkky** [comment]
> 

大佬有空就维护更新下插件吧，谢谢了
